# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghx < Formula
  desc "GitHub code exploration for AI agents"
  homepage "https://github.com/gkoreli/ghx"
  version "2.9.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gkoreli/ghx/releases/download/v2.9.0/ghx_darwin_amd64.tar.gz"
      sha256 "4e30727ac62f6d46e6a1371a831c52bc2a8834ef1997f74e380fca1c980d36f3"

      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL-ghx.md"
        prefix.install "SKILL-ghx-mcp.md"
        prefix.install "SKILL-ghx-recon.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gkoreli/ghx/releases/download/v2.9.0/ghx_darwin_arm64.tar.gz"
      sha256 "3fb62ba7617f679ab1adcdfcba501b6036e6b46422d97206618f479e997cbd1b"

      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL-ghx.md"
        prefix.install "SKILL-ghx-mcp.md"
        prefix.install "SKILL-ghx-recon.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gkoreli/ghx/releases/download/v2.9.0/ghx_linux_amd64.tar.gz"
      sha256 "c6c4839fabfb53acfb118825123f0dd9e9b0293c53b132735810a25678c401b2"
      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL-ghx.md"
        prefix.install "SKILL-ghx-mcp.md"
        prefix.install "SKILL-ghx-recon.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gkoreli/ghx/releases/download/v2.9.0/ghx_linux_arm64.tar.gz"
      sha256 "6c8a92ebc946dece1cdfae83fedcbb83bd0f2fc8910280fa91deeac5c98b4d5a"
      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL-ghx.md"
        prefix.install "SKILL-ghx-mcp.md"
        prefix.install "SKILL-ghx-recon.md"
      end
    end
  end
end
