# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghx < Formula
  desc "GitHub code exploration for AI agents"
  homepage "https://github.com/gkoreli/ghx"
  version "2.1.15"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gkoreli/ghx/releases/download/v2.1.15/ghx_darwin_amd64.tar.gz"
      sha256 "61ebf141c2ad18e803f4e02625ab89909cf43f6ae304b2afe3280b706cdf4bf9"

      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL.md"
        prefix.install "MCP-SKILL.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gkoreli/ghx/releases/download/v2.1.15/ghx_darwin_arm64.tar.gz"
      sha256 "d0eee2f8b5d53b23150cf6b436b2aebcebecbf1e63c7d89b3f68928de3ad2370"

      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL.md"
        prefix.install "MCP-SKILL.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gkoreli/ghx/releases/download/v2.1.15/ghx_linux_amd64.tar.gz"
      sha256 "e42bd53004a0d6c94ac0bf51013aec297a90a4599ff9bb073ea739ee3594f5cf"
      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL.md"
        prefix.install "MCP-SKILL.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gkoreli/ghx/releases/download/v2.1.15/ghx_linux_arm64.tar.gz"
      sha256 "e26bca6434fb1c8090d23b71caa2f6cc09d172ea21060028c6eac712c7c43638"
      define_method(:install) do
        bin.install "ghx"
        prefix.install "SKILL.md"
        prefix.install "MCP-SKILL.md"
      end
    end
  end
end
